package controller;


import DAO.*;
import Utilities.TimeTools;
import javafx.collections.FXCollections;
import javafx.collections.ObservableList;
import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.Alert;
import javafx.scene.control.ButtonType;
import javafx.scene.control.ComboBox;
import javafx.scene.control.TextField;
import javafx.stage.Stage;
import model.Country;
import model.Customer;
import model.FirstLevelDivision;
import model.User;

import java.sql.Timestamp;
import java.time.Instant;

/**
 * Controller for CreateEditCustomerForm
 */
public class CreateEditCustomerFormController {

    /**
     * Textfield that holds the customer ID. Will hold the value of auto generated or the actual ID of the edited customer.
     */
    public TextField inputCustomerId;
    /**
     * Textfield that holds the customer name. Valid as long as it isn't empty.
     */
    public TextField inputName;
    /**
     * The textfield that holds the customer's address. valid as long as it isn't empty.
     */
    public TextField inputAddress;
    /**
     * The textfield that holds the customer's zip code. Valid as long as it isn't empty.
     */
    public TextField inputPostalCode;

    /**
     * The textfield that holds the customer's phone number. Valid as long as it isn't empty.
     */
    public TextField inputPhone;
    /**
     * The textfield that holds the customer's divisionId. This field is disabled and autogenerated from the selected country and division comboboxes.
     */
    public TextField inputDivisionId;
    /**
     * The combobox containing all values of the selected country, generated from the country combobox selected value.
     */
    public ComboBox inputDivision;
    /**
     * The combobox that holds which contry the user is in. Changing this will populate the division combobox with the appropriate divisions of that country.
     */
    public ComboBox inputCountry;
    /**
     * keeps track of the customer being edited if there is one.
     */
    public Customer existingCustomer;

    /**
     * keeps track of the logged in user obtained from the login form. gets passed around the application.
     */
    private User loggedInUser = null;

    /**
     * getter for the logged in user.
     * @return returns the logged in user.
     */
    public User getLoggedInUser() {
        return loggedInUser;
    }

    /**
     * setter for the logged in user.
     * @param loggedInUser the logged in user to set the value to
     */
    public void setLoggedInUser(User loggedInUser) {
        this.loggedInUser = loggedInUser;
    }

    /**
     * Checks if the inputs are valid and returns false if any of them aren't. All inputs are valid as long as there is some input.
     * @return
     */
    private boolean isFormInputValid()
    {
        if(inputName.getText().length() == 0)
        {
            Alert alert = new Alert(Alert.AlertType.ERROR, "Please make sure the Customer's Name is filled out",ButtonType.OK);
            alert.showAndWait();
            return false;
        }
        if(inputAddress.getText().length() == 0)
           {
               Alert alert = new Alert(Alert.AlertType.ERROR, "Please make sure the Customers Address is filled out.",ButtonType.OK);
               alert.showAndWait();
               return  false;
           }
        if(inputPostalCode.getText().length() == 0)
            {
                Alert alert = new Alert(Alert.AlertType.ERROR, "Please make sure the Customer's Postal-code is filled out",ButtonType.OK);
                alert.showAndWait();
                return false;
            }
        if(inputPhone.getText().length() == 0)
            {
                Alert alert = new Alert(Alert.AlertType.ERROR, "Please make sure the Customer's phone number is filled out.",ButtonType.OK);
                alert.showAndWait();
                return false;
            }
        if(inputDivision.getSelectionModel().getSelectedItem() == null)

            {
                Alert alert = new Alert(Alert.AlertType.ERROR, "Please make sure a First Level Division is selected.",ButtonType.OK);
                alert.showAndWait();
                return false;
            }
        if(inputCountry.getSelectionModel().getSelectedItem() == null)
            {
                Alert alert = new Alert(Alert.AlertType.ERROR, "Please make sure a Country is selected..",ButtonType.OK);
                alert.showAndWait();
                return false;
            }
        return true;
    }

    /**
     * Helper method to determine if a customer is being edited.
     * @return returns true if the value of the customerID input is filled with a number. If it isnt, then the appointment is new.
     */
    private boolean creatingNewCustomer()
    {
        return inputCustomerId.getText().matches("\\d+");
    }


    /**
     * getter for the existing customer
     * @return returns the existing customer
     */
    public Customer getExistingCustomer() {
        return existingCustomer;
    }

    /**
     * setter the existing customer.
     * @param existingCustomer the existingCustomer to set the value to.
     */
    public void setExistingCustomer(Customer existingCustomer) {
        this.existingCustomer = existingCustomer;
    }

    /**
     * Returns to the Customer Management form
     */
    private void returnToManagementForm() {
        try {

            FXMLLoader fxmlLoader = new FXMLLoader(getClass().getResource("/view/ManagementForm.fxml"));
            Parent managementWindow = fxmlLoader.load();
            Scene ModifyPartScene = new Scene(managementWindow);
            Stage window = (Stage) inputCustomerId.getScene().getWindow();
            CustomerManagerController controller = fxmlLoader.getController();
            controller.setLoggedInUser(getLoggedInUser());
            window.setScene(ModifyPartScene);
            window.show();
        }
        catch (Exception ex)
        {
            Alert alert = new Alert(Alert.AlertType.ERROR, ex.getMessage() ,ButtonType.OK);
            alert.showAndWait();
        }
    }

    /**
     * populates the form with the existing customer and sets combobox values as well.
     * @param existingCustomer the existing customer carried over from the customer manager form.
     */
    public void setupExistingCustomer(Customer existingCustomer)
    {
        inputCustomerId.setText(String.valueOf(existingCustomer.getCustomerId()));
        inputName.setText((existingCustomer.getCustomerName()));
        inputAddress.setText(existingCustomer.getAddress());
        inputPostalCode.setText(existingCustomer.getPostalCode());
        inputPhone.setText(existingCustomer.getPhone());
        inputDivisionId.setText((String.valueOf(existingCustomer.getDivisionId())));
        ICountriesDao ICountriesDao = new CountriesDaoImplSql();
        IFirstLevelDivisionsDao IFirstLevelDivisionsDao = new FirstLevelDivisionsDaoImplSql();
        FirstLevelDivision fld = IFirstLevelDivisionsDao.getAllFirstLevelDivisions().stream().filter(firstLevelDivision -> firstLevelDivision.getDivisionId() == existingCustomer.getDivisionId()).findFirst().get();
        inputDivision.getSelectionModel().select(fld.getDivision());
        Country existingCountry = ICountriesDao.getAllCountries().stream().filter(country ->  country.getCountryId() == fld.getCountyId()).findFirst().orElse(null);
        inputCountry.getSelectionModel().select(existingCountry.getCountry());
        ObservableList<FirstLevelDivision> matchingDivisions = FXCollections.observableArrayList();
        IFirstLevelDivisionsDao.getAllFirstLevelDivisions().stream().filter(firstLevelDivision -> firstLevelDivision.getCountyId() == fld.getCountyId()).forEach(firstLevelDivision -> matchingDivisions.add(firstLevelDivision));
        ObservableList<String> divisionNames = FXCollections.observableArrayList();
        matchingDivisions.forEach(firstLevelDivision -> divisionNames.add(firstLevelDivision.getDivision()));
        inputDivision.setItems(divisionNames);
        this.setExistingCustomer(existingCustomer);
        ICustomerDao ICustomerDao = new ICustomerDaoImplSql();
        ICustomerDao.getAllCustomers().forEach(customer -> customer.setCustomerId((ICustomerDao.getAllCustomers().get(0).getDivisionId())));
    }

    /**
     * populates the combobox for country with its values.
     */
    private void setupCountryComboboxSource()
    {
        ObservableList<String> countryNames = FXCollections.observableArrayList();
        ICountriesDao ICountriesDao = new CountriesDaoImplSql();
        ICountriesDao.getAllCountries().forEach((country) -> countryNames.add(country.getCountry()));
        inputCountry.setItems(countryNames);
    }


    /**
     * Runs on form load. Runs the setupCountryComboboxSource() method and also sets the title.
     */
    @FXML
    public void initialize()
    {
        Stage openWindow = (Stage) Stage.getWindows().stream().filter((window) -> window.isShowing()).findFirst().get();
        setupCountryComboboxSource();
        openWindow.setTitle("Add/Edit Customer");
    }


    /**
     * Saves the customer as a new customer to database or edits the already existing customer. if any of the inputs are invalid then an error message will be thrown from
     * the isFormInputValid() method. New customers will display that the value for ID is autogenerated and unusable. Edited customers will have their ID from the database in the field.
     * Event handler for the save button.
     */
    public void saveCustomer() {
        if(!isFormInputValid())
            return;

        try {


            if (creatingNewCustomer()) {
                Customer c = new Customer();
                c.setCustomerId(Integer.parseInt(inputCustomerId.getText()));
                c.setCustomerName(inputName.getText());
                c.setAddress(inputAddress.getText());
                c.setPhone(inputPhone.getText());
                c.setPostalCode(inputPostalCode.getText());
                c.setCreateDate(TimeTools.ConvertDateToUTC(Timestamp.from(Instant.now())));
                c.setCreateDate(getExistingCustomer().getCreateDate());
                c.setCreatedBy(getExistingCustomer().getCreatedBy());
                c.setLastUpdate(TimeTools.ConvertDateToUTC(Timestamp.from(Instant.now())));
                c.setLastUpdatedBy(loggedInUser.getUserName());
                c.setDivisionId((Integer.parseInt(inputDivisionId.getText())));
                if (isFormInputValid()) {
                    ICustomerDao ICustomerDao = new ICustomerDaoImplSql();
                    ICustomerDao.updateCustomer(c.getCustomerId(), c);
                }

            } else {
                Customer c = new Customer();
                c.setCustomerName(inputName.getText());
                c.setAddress(inputAddress.getText());
                c.setPhone(inputPhone.getText());
                c.setPostalCode(inputPostalCode.getText());
                c.setCreateDate(TimeTools.ConvertDateToUTC(Timestamp.from(Instant.now())));
                c.setCreatedBy(loggedInUser.getUserName());
                c.setLastUpdate(TimeTools.ConvertDateToUTC(Timestamp.from(Instant.now())));
                c.setLastUpdatedBy(loggedInUser.getUserName());
                c.setDivisionId((Integer.parseInt(inputDivisionId.getText())));

                ICustomerDao ICustomerDao = new ICustomerDaoImplSql();
                ICustomerDao.addCustomer(c);

            }

            returnToManagementForm();
        }
        catch (Exception ex)
        {
            Alert alert = new Alert(Alert.AlertType.ERROR, ex.getMessage() ,ButtonType.OK);
            alert.showAndWait();
        }
    }

    /**
     * event handler for the cancel button, returns to the management form
     */
    public void discardCustomer() {
        returnToManagementForm();
    }

    /**
     * Event handler for when a country is selected from the country combobox. sets the CountryId to the matching value, as well as sets up the data in the First Level Division text area
     */
    public void countrySelected(){
        inputDivision.setItems(null);
        ICountriesDao ICountriesDao = new CountriesDaoImplSql();
        String selectedOption = (String)inputCountry.getValue();
        int selectedCountryId = ICountriesDao.getAllCountries().stream().filter(x -> x.getCountry().equals(selectedOption)).findFirst().get().getCountryId();

        IFirstLevelDivisionsDao IFirstLevelDivisionsDao = new FirstLevelDivisionsDaoImplSql();
        ObservableList<String> matchingFirstLevelDivisions = FXCollections.observableArrayList();
        IFirstLevelDivisionsDao.getAllFirstLevelDivisions().stream().filter(x -> x.getCountyId() == selectedCountryId).forEach((firstLevelDivision -> matchingFirstLevelDivisions.add(firstLevelDivision.getDivision())));
        inputDivision.setItems(matchingFirstLevelDivisions);

    }


    /**
    *Event handler for when the combobox for when the user picks a value from the list. sets the divisionId for the user
     */
        public void divisionSelected() {

        String selectedOption = (String)inputDivision.getValue();
        if(selectedOption != null)
        {
            IFirstLevelDivisionsDao IFirstLevelDivisionsDao = new FirstLevelDivisionsDaoImplSql();
            int divisionId = IFirstLevelDivisionsDao.getAllFirstLevelDivisions().stream().filter((x) -> x.getDivision().equals(selectedOption)).findFirst().get().getDivisionId();
            inputDivisionId.setText(String.valueOf(divisionId));
        }
    }
    }
